### ISSUE TITLE
Finsih CPP module09

### ISSUE THREAD

**Issue by Daniexp** [Daniexp/CPP#1]
## Finish CPP module 09

**Description**
Finish the module09

**Acceptance Criteria**
- [x]  All exercises in the module finished
- [x]  Code ready to be moved to the intra repo

**Subtasks**
- [x] Finish ex02
- [x] Review ex00
- [x] Review ex01
- [x] Review ex02
- [x] Ready  for the intra repo

**Estimated Time**
- 8 hours / 2 days

**Additional Context**

Member | Refinement Agree |
---- | --- |
Jsanfeli |  |
Ndonaire |  |
Dexposit| Yes|

**Comment by Daniexp** [comment]
## Subtask Status - Finish ex02
### Status: The ex02 wasn't shorting correctly with the vector.
### Bugs encountered in the method today (checked fixec ones)
- [x] void binarySearchInsertion(vector& S, const unsigned int srcValue, int start, int end);
- [x] insertPowerTwoGroupsByBinarySearchInSubsequences(vector& src, vector& shorted, std::vector<int>& pairs);
### TO DO
- [x] Finish review ex00 vector short
- [x] Translate finished vector short to the list short
- [ ] Implement time counters and prints of the time differences between vector and list short
- [ ] Review ex02 like a correction

**Comment by Daniexp** [comment]
.

**Comment by Daniexp** [comment]
**All the task are a finished**
